spring:
  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    encoding:
      force-response: true
  port: 8800

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: desc
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /**

loadrover:
  gatling:
    path: gatling/src/gatling/resources/static
    source: source
    work: work
    progress: progress
    result: result
  output:
    class-name-prefix: "local"