spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mariadb://localhost:3306/loadrover
    username: root
    password: hiworld
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        auto_quote_keyword: true
  servlet:
    multipart:
      max-file-size: 1600KB

server:
  servlet:
    encoding:
      charset: UTF-8
  port: 8800

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: desc
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /**

cloud:
  aws:
    credentials:
      access-key: AKIA34W5ZACHXML3ROOM
      secret-key: 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  #추후 변경필요.
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: dev-sg-admin-static
      cloud-front-domain: d1ipvhagx28fo9.cloudfront.net

loadrover:
  download-directory: api/src/main/resources/static/apache-jmeter-5.6.3/bin
  working-directory: api/src/main/resources/static/apache-jmeter-5.6.3/bin
  report-directory: api/src/main/resources/static/apache-jmeter-5.6.3/bin/report