spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mariadb://10.88.12.137:13306/loadrover_dev
    username: loadrover_dev
    password: loadrover_dev_0525!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    defer-datasource-initialization: true
    show-sql: true
    generate-ddl: true
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        auto_quote_keyword: true
  servlet:
    multipart:
      max-file-size: 1600KB

server:
  servlet:
    encoding:
      charset: UTF-8
  port: 8800

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: desc
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /**

loadrover:
  gatling:
    path: ../../app/etc/gatling/src/gatling/resources/static
    source: source
    progress: progress
    work: work
    work-path: ../../app/etc/gatling/src/gatling/kotlin
    complete: complete
    result: result
  output:
    class-name-prefix: "dev"

cloud:
  aws:
    credentials:
      access-key: AKIA34W5ZACHXML3ROOM
      secret-key: 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  #추후 변경필요.
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: dev-sg-admin-static
      cloud-front-domain: d1ipvhagx28fo9.cloudfront.netc