version: "3.8"

services:
  api:
#    build:
#      context: .
#      dockerfile: Dockerfile.dev
    image: 2bytesdev/loadrover-io:api
    container_name: api
    ports:
      - "8800:8800"
    environment:
      - SPRING_PROFILES_ACTIVE=dev # 환경 변수 설정
      - TZ=Asia/Seoul # 타임존 설정
#    networks:
#      - load-test-network
#
#networks:
#  load-test-network:
#    driver: bridge
