version: '3.8'

services:
  load-test-be:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: load-test-be
    ports:
      - "3020:8800"
    environment:
      - SPRING_PROFILES_ACTIVE=dev  # 환경 변수 설정
      - TZ=Asia/Seoul # 타임존 설정
    networks:
      - load-test-network
    volumes:
      -../gatling:/app/etc

networks:
  load-test-network:
    name: load-test-network