FROM openjdk:17-jdk as build

WORKDIR /app

COPY gradlew .
COPY gradle gradle
COPY build.gradle.kts .
COPY settings.gradle.kts .

RUN chmod +x ./gradlew && ./gradlew clean build --no-daemon -x test

COPY src src
RUN ./gradlew build --no-daemon -x test

FROM openjdk:17-jre-slim

WORKDIR /app

COPY --from=build /app/build/libs/*.jar application.jar

EXPOSE 8800

ENTRYPOINT ["java","-Dspring.profiles.active=dev","-jar","application.jar"]
