version: '3.8'

services:
  oad-test-be:
    build:
      context:
        dockerfile: Dockerfile
    container_name: load-test-be
    ports:
      - "3020:3000"
    environment:
      - SPRING_PROFILES_ACTIVE=dev  # 환경 변수 설정
      - TZ=Asia/Seoul # 타임존 설정
    networks:
      - load-test-network
#    volumes:
#      - /home/bcat_be/dev-be-log/loadrover/opt/workspace/logs

networks:
  load-test:
    name: load-test-network