name: loadrover-io

on:
  push:
    branches:
      - "dev"
    tags:
      - 'loadrover-dev-[0-9]+.[0-9]+.[0-9]+' # release tag

jobs:
  build-and-push:
    name: build-and-push
    runs-on: [self-hosted, loadrover-io-dev] # loadrover-io-dev 라는 라벨의 self-hosted runner 사용
    steps:
      # docker-compose install
      - name: Install Docker Compose
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt-get update
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S apt-get install -y docker-compose

      # docker-compose.yml 파일 복사
      - name: Checkout code
        uses: actions/checkout@v3

      # gradle build 를 위한 jdk 사용
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # ./gradlew 권한 설정
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      # gradle build (배포할 프로젝트 jar 파일 생성)
      - name: Build with Gradle
        run: ./gradlew clean :api:build --exclude-task test
        shell: bash

      # docker image run
      - name: Docker Compose up
        run: |
          cd /home/bcat_be/loadrover/actions-runner/_work/2bytes.loadrover-server/2bytes.loadrover-server/api
          
          if docker-compose ps -q load-test-be >/dev/null; then
            docker-compose stop
            
          docker rmi $(docker images '*load-test-be*' -q) || true
          fi
            docker-compose build && 
            docker-compose up -d